
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxlqzpsycfusyjrkcxgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4bHF6cHN5Y2Z1c3lqcmtjeGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Mjk1OTcsImV4cCI6MjA2NTMwNTU5N30.YTvRncJZdSEG-pi4MD8umm8h9YWGgnXsspHqEFi7ivw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
